### ISSUE TITLE
ESP32 Compatibility

### ISSUE THREAD

**Issue by martincollado** [NHBSystems/NHB_AD7794#1]
¿The library was tested against an ESP32 board?

**Comment by jjuliano77** [comment]
No, but I will try it out. I think I have one available to try, but I may have to order one first.

**Comment by martincollado** [comment]
Great! I bought an AD7794 FeatherWing from Tindie and finally the product arrived today. On the next weeks probably I’ll start a new project based on ESP32 board with a few sensors. In case that I found some bugs I’ll reported here.

**Comment by jjuliano77** [comment]
I tested with a NodeMCU ESP32s. It did not work initially but I have got it working now. The biggest issue was that there was a nested call to SPI.beginTransaction() that was causing the esp32 to lockup. This is apparently due to the esp32 SPI library using a mutex lock on the SPI transaction. It took a while to figure out, but only required a minor change to fix.

The fix is included in the last commit. Please clone/download the repo to get the latest.

**Comment by martincollado** [comment]
Thanks for the update! I'll try it and in case of problems open new issue. I close this one.
